package com.linkforty.sdk.models

import com.squareup.moshi.JsonClass

/**
 * Response from the install attribution API.
 */
@JsonClass(generateAdapter = true)
data class InstallResponse(
    /** Unique install ID generated by the backend */
    val installId: String,

    /** Whether this install was attributed to a link click */
    val attributed: Boolean,

    /** Confidence score for attribution (0-100) */
    val confidenceScore: Double,

    /** Which fingerprint factors matched */
    val matchedFactors: List<String>,

    /** Deep link data if attributed, null if organic */
    val deepLinkData: DeepLinkData? = null
)
